# Generated by Django 4.2.7 on 2026-04-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in current 8-day cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('rest', 'Rest Break (30 min)'), ('sleep', 'Sleep / Off Duty (10 hrs)'), ('fuel', 'Fuel Stop')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('arrival_time', models.FloatField(help_text='Hours from trip start')),
                ('duration', models.FloatField(help_text='Duration in hours')),
                ('miles_from_start', models.FloatField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
        ),
    ]
